language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  include:
    - php: 7.0
      env: PHPUNIT_FLAGS="--coverage-clover coverage.clover" CHECK_CS=true

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - if [[ "$CHECK_CS" != "" ]]; then composer require symplify/coding-standard; fi

script:
  - phpunit $PHPUNIT_FLAGS
  - if [[ "$CHECK_CS" != "" ]]; then vendor/bin/symplify-cs check src Tests; fi

after_script:
  - if [[ "$PHPUNIT_FLAGS" != "" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
